### ISSUE TITLE
12.2 Don't allow edits of manual groups/waiting lists if my user restriction is on

### ISSUE THREAD

**Issue by SamRimmer17** [mattparker/lamplighthelp#117]
If user restriction on don’t allow manual groups/waiting lists edits.

**Comment by LibbyBrookes** [comment]
It's now not possible to edit manual groups/wiating lists if your access is limited by a 'my user' restriction. This is because a person with this restriction wouldn't see existing members on the list, and then saving it would mean that LL deleted those 'hidden' members from the list, creating issues for other users. A note needs adding to 12.6 - editing lists, as well as 30.2 Managing Waiting Lists from the Menu Bar.
